<?php

namespace NameFindProject\src\Finders;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-25 at 14:37:27.
 */
class NameFinderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var NameFinder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NameFinder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    public function test()
    {
        $this->assertEquals(0, $this->object->replaceSingleArticle(176267));
    }
}
