<?php

namespace NameFindProject\src\DB\DB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-25 at 14:37:28.
 */
class DbWorkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DbWork
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DbWork;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

}
